sudo: required

services:
  - docker

# skip the installation.
install: true

script:
  - docker-compose up -d
  - docker-compose run --rm api bundle exec rake

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=alejandrodevs/dockerapp
  - docker build -t $REPO:$COMMIT .
  - docker push $REPO:$COMMIT
