sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=alejandrodevs/dockerapp-api
    - REGISTRY_USER=myrobot
    - REGISTRY_PASS=...

before_install:
  - docker-compose --version

before_script:
  - echo 'Testing Docker Hub credentials'

script:
  - docker-compose up -d
  - docker-compose ps
