sudo: required

services:
  - docker

env:
  global:
    # Docker login credentials are set in TravisCI.
    - DOCKER_REPO=alejandrodevs/dockerapp

# skip the installation.
before_install: true
install: true

script:
  - docker-compose build
  - docker-compose run --rm api bundle exec rake

after_success:
  - echo $TRAVIS_COMMIT
  - docker login --username=$DOCKER_USER --password=$DOCKER_PASS
  - docker build -t $DOCKER_REPO:$TRAVIS_COMMIT .
  - docker push $DOCKER_REPO:$TRAVIS_COMMIT
