sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=alejandrodevs/dockerapp-api
    - REGISTRY_USER=myrobot
    - REGISTRY_PASS=...

script:
  - docker-compose up -d
  - docker-compose ps
  - docker-compose run --rm api bundle exec rake
