sudo: required

services:
  - docker

# skip the installation.
install: true

script:
  - docker-compose up -d
  - docker images
  - docker-compose run --rm api bundle exec rake

after_success:
  - docker login --username=$DOCKER_USER --password-stdin=$DOCKER_PASS
  - export REPO=alejandrodevs/dockerapp
  - docker build -t alejandrodevs/dockerapp:v2 .
  - docker push alejandrodevs/dockerapp:v2
