version: '3'

volumes:
  db_data:
  redis_data:

services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis_data:/var/lib/redis/data

  sidekiq:
    build: .
    image: alejandrodevs/docker-api
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/docker-api
    depends_on:
      - db
      - redis

  api:
    build: .
    image: alejandrodevs/docker-api
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/docker-api
    ports:
      - 3000:3000
    depends_on:
      - db
