apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-api
  template:
    metadata:
      labels:
        app: docker-api
    spec:
      containers:
      - name: docker-api
        image: alejandrodevs/docker-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
