apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-api-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-api-db
  template:
    metadata:
      labels:
        app: docker-api-db
    spec:
      containers:
      - name: docker-api-db
        image: postgres
        ports:
        - containerPort: 5432
