apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-api-sidekiq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-api-sidekiq
  template:
    metadata:
      labels:
        app: docker-api-sidekiq
    spec:
      containers:
      - name: docker-api-sidekiq
        image: alejandrodevs/docker-api
        imagePullPolicy: IfNotPresent
