kind: Service
apiVersion: v1
metadata:
  name: docker-api-service
spec:
  selector:
    app: docker-api
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
status:
  loadBalancer: {}
