apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-api-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-api-redis
  template:
    metadata:
      labels:
        app: docker-api-redis
    spec:
      containers:
      - name: docker-api-redis
        image: redis
        ports:
        - containerPort: 6379
